"""empty message

Revision ID: 8d0e7a4f1b85
Revises: 4f6e8af699ca
Create Date: 2022-08-11 14:07:39.501690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0e7a4f1b85'
down_revision = '4f6e8af699ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description2', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description2')
    # ### end Alembic commands ###
